<?php
use VCAC\LandingPage as Notice;

check_vcac(Notice\emergency_markup()==='', 'Emergency banner is absent by default');
$expiry=(new DateTimeImmutable('+2 days',new DateTimeZone('America/Vancouver')))->format('Y-m-d\TH:i');
$notice=array('enabled'=>'1','tone'=>'red','expires'=>$expiry,'url'=>'https://example.test/english/announcements/closure/','copy'=>array('en'=>array('title'=>'Sunday services cancelled','message'=>"The church building is closed due to snow.\nPlease join worship online.",'link'=>'Read the announcement')));
$valid=Notice\emergency_validate($notice);
check_vcac(!is_wp_error($valid)&&$valid['tone']==='red','Staff can select a red notice and Announcement link');
check_vcac($valid['expires_at']===(new DateTimeImmutable($expiry,new DateTimeZone('America/Vancouver')))->getTimestamp(),'Expiry is interpreted in Vancouver time');
check_vcac(Notice\emergency_active($valid,$valid['expires_at']-1)&&!Notice\emergency_active($valid,$valid['expires_at']),'Notice expires at the exact configured time');
$invalid=$notice;$invalid['expires']='';
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Active notice needs an expiry');
$invalid['expires']='2026-03-08T02:30';
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Nonexistent daylight-saving time is rejected');
$invalid=$notice;$invalid['expires']='2020-01-01T12:00';
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Past expiry cannot activate a notice');
$invalid=$notice;$invalid['copy']['en']['message']='';
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Empty English message cannot activate a notice');
$invalid=$notice;$invalid['copy']['zh-Hant']=array('title'=>'Only a heading');
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Partial translation is rejected');
$invalid=$notice;$invalid['url']='javascript:alert(1)';
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Script links are rejected');
$invalid=$notice;$invalid['copy']['en']['title']=str_repeat('a',121);
check_vcac(is_wp_error(Notice\emergency_validate($invalid)),'Overlong heading is rejected');
check_vcac(is_wp_error(Notice\emergency_validate('invalid')),'Malformed notice input is rejected');
$nonce=wp_create_nonce('vcac_emergency_save');
check_vcac(!is_wp_error(Notice\emergency_save($notice,$nonce))&&Notice\emergency_active(),'Administrator can save an active notice');
check_vcac(is_wp_error(Notice\emergency_save(array(),'invalid'))&&Notice\emergency_active(),'Invalid nonce preserves the saved notice');
$editor=wp_insert_user(array('user_login'=>'notice_editor','user_pass'=>'local-test-only','role'=>'editor'));
wp_set_current_user($editor);
$notice['tone']='yellow';
check_vcac(!is_wp_error(Notice\emergency_save($notice,wp_create_nonce('vcac_emergency_save'))),'Main-site Editor can manage the notice');
wp_set_current_user(0);
check_vcac(is_wp_error(Notice\emergency_save(array(),wp_create_nonce('vcac_emergency_save')))&&Notice\emergency_active(),'Anonymous visitor cannot change the notice');
wp_set_current_user(1);switch_to_blog($sites['en']);
check_vcac(!Notice\emergency_active()&&is_wp_error(Notice\emergency_save($notice,wp_create_nonce('vcac_emergency_save'))),'Ministry site cannot read or save the main-site emergency notice');
restore_current_blog();
$markup=Notice\emergency_markup();
check_vcac(strpos($markup,'data-notice-language="en"')!==false&&strpos($markup,'href="https://example.test/english/announcements/closure/"')!==false,'English fallback and Announcement link render without JavaScript');
$notice['copy']['zh-Hant']=array('title'=>'主日崇拜取消','message'=>'教會因大雪暫停開放。請參加網上崇拜。','link'=>'閱讀公告');
$notice['copy']['zh-Hans']=array('title'=>'主日崇拜取消','message'=>'教会因大雪暂停开放。请参加网上崇拜。','link'=>'阅读公告');
$notice['tone']='red';
Notice\emergency_save($notice,wp_create_nonce('vcac_emergency_save'));
$markup=Notice\emergency_markup();
check_vcac(strpos($markup,'data-tone="red"')!==false&&substr_count($markup,'data-notice-language=')===3,'Red banner contains all three language versions');
$unsafe=Notice\emergency_settings();$unsafe['copy']['en']['title']='<img src=x onerror=alert(1)>';
check_vcac(strpos(Notice\emergency_markup($unsafe),'<img src=x')===false,'Stored notice text is escaped on output');
query_vcac($landing);ob_start();Notice\render();$notice_page=ob_get_clean();
check_vcac(strpos($notice_page,'id="vcac-emergency"')<strpos($notice_page,'<header class="header">')&&strpos($notice_page,'site/emergency.js?ver=')!==false,'Banner is integrated above the header with packaged scripts');
file_put_contents('/test-output/emergency-rendered.html',$notice_page);
ob_start();Notice\emergency_admin();$admin_html=ob_get_clean();
file_put_contents('/test-output/emergency-admin-fragment.html',$admin_html);
check_vcac(strpos($admin_html,'name="notice[tone]"')!==false&&strpos($admin_html,'name="_wpnonce"')!==false,'Staff editor contains colour control and save nonce');
unset($notice['enabled']);Notice\emergency_save($notice,wp_create_nonce('vcac_emergency_save'));
check_vcac(Notice\emergency_markup()===''&&Notice\emergency_settings()['copy']['en']['title']==='Sunday services cancelled','Disabling hides notice while preserving its text');
delete_option(Notice\EMERGENCY_OPTION);
