<?php
// Runs within integration.php's disposable local Multisite network.
switch_to_blog($sites['en']);
wp_set_current_user(1);
$crop_post = $shared;
check_vcac(VCAC\LandingPage\card_image_settings($crop_post) === array('imageFit'=>'cover','imagePositionX'=>50,'imagePositionY'=>50), 'Existing listings default to centred auto-fill without a migration');
$crop_save = function ($id, $fit, $x, $y) use ($future) {
    $_POST = array('vcac_content_listing_nonce'=>wp_create_nonce('vcac_save_content_listing'),'vcac_listing'=>'community','vcac_schedule'=>'Wednesdays','vcac_review_until'=>$future,'vcac_image_fit'=>$fit,'vcac_image_x'=>$x,'vcac_image_y'=>$y);
    wp_update_post(array('ID'=>$id));
};
$crop_save($crop_post,'cover','12','83');
check_vcac(VCAC\LandingPage\card_image_settings($crop_post) === array('imageFit'=>'cover','imagePositionX'=>12,'imagePositionY'=>83), 'Staff crop positions persist through real save_post hooks');
$crop_save($crop_post,'contain','12','83');
check_vcac(VCAC\LandingPage\card_image_settings($crop_post)['imageFit']==='contain', 'Poster mode persists and preserves crop coordinates for switching back');
restore_current_blog();
$crop_feed=VCAC\LandingPage\feed_payload();
$crop_record=array_values(array_filter($crop_feed['locales']['en']['community'],function($item)use($sites,$crop_post){return $item['id']===$sites['en'].':'.$crop_post;}))[0];
check_vcac($crop_record['imageFit']==='contain' && $crop_record['imagePositionX']===12 && $crop_record['imagePositionY']===83, 'Cross-site public feed carries each listing crop settings');
switch_to_blog($sites['en']);
$crop_save($crop_post,'injected','-30','999');
check_vcac(VCAC\LandingPage\card_image_settings($crop_post) === array('imageFit'=>'cover','imagePositionX'=>0,'imagePositionY'=>100), 'Invalid modes fall back safely and out-of-range positions clamp');
$crop_save($crop_post,array('contain'),array(20),'not-a-number');
check_vcac(VCAC\LandingPage\card_image_settings($crop_post) === array('imageFit'=>'cover','imagePositionX'=>50,'imagePositionY'=>50), 'Malformed crop form values cannot inject CSS or break saving');
$crop_save($crop_post,'cover','15','85');
$_POST['vcac_content_listing_nonce']='invalid';$_POST['vcac_image_x']=99;
wp_update_post(array('ID'=>$crop_post));
check_vcac(VCAC\LandingPage\card_image_settings($crop_post)['imagePositionX']===15, 'Invalid nonce cannot change cropping');
wp_set_current_user(0);$_POST['vcac_content_listing_nonce']=wp_create_nonce('vcac_save_content_listing');
wp_update_post(array('ID'=>$crop_post));
check_vcac(VCAC\LandingPage\card_image_settings($crop_post)['imagePositionX']===15, 'Unauthorised user cannot change cropping');
wp_set_current_user(1);$_POST=array();wp_update_post(array('ID'=>$crop_post,'post_title'=>'Crop source revised'));
check_vcac(VCAC\LandingPage\card_image_settings($crop_post)['imagePositionX']===15, 'Quick/API edits without crop fields preserve saved cropping');
if(!post_type_exists('mec-events')) register_post_type('mec-events',array('public'=>true,'supports'=>array('title','thumbnail')));
$crop_event=wp_insert_post(array('post_type'=>'mec-events','post_status'=>'draft','post_title'=>'Local crop test event'));
$crop_save($crop_event,'cover',27,73);
check_vcac(VCAC\LandingPage\card_image_settings($crop_event)['imagePositionY']===73, 'MEC event editor uses the same saved crop settings');
$bytes=file_get_contents(WP_PLUGIN_DIR.'/vcac-landing-page/site/assets/congregation.jpg');
$upload=wp_upload_bits('crop-test-building.jpg',null,$bytes);
$attachment=wp_insert_attachment(array('post_mime_type'=>'image/jpeg','post_title'=>'Crop test image','post_status'=>'inherit'),$upload['file']);
wp_update_attachment_metadata($attachment,array('width'=>1500,'height'=>1035,'file'=>_wp_relative_upload_path($upload['file'])));
update_post_meta($crop_event,'_thumbnail_id',$attachment);
$original_hash=hash_file('sha256',$upload['file']);
$original_meta=get_post_meta($attachment,'_wp_attachment_metadata',true);
$crop_save($crop_event,'contain',0,100);
check_vcac(hash_file('sha256',$upload['file'])===$original_hash && get_post_meta($attachment,'_wp_attachment_metadata',true)===$original_meta && get_post_thumbnail_id($crop_event)===$attachment, 'Cropping leaves original file, attachment metadata and featured-image selection unchanged');
ob_start();VCAC\LandingPage\render_listing_box(get_post($crop_event));$crop_box=ob_get_clean();
check_vcac(strpos($crop_box,'name="vcac_image_x"')!==false && strpos($crop_box,'name="vcac_image_y"')!==false && strpos($crop_box,'Show full image')!==false && strpos($crop_box,'vcac-crop-preview')!==false, 'Event listing box renders labelled crop controls, poster mode and preview');
file_put_contents('/test-output/crop-editor.html',$crop_box);
file_put_contents('/test-output/crop-event.json',wp_json_encode(array('site'=>$sites['en'],'post'=>$crop_event)));
$_POST=array();restore_current_blog();
